// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/aatmikjain/Documents/go-mux/apis/store_controller.go

// Package mock_apis is a generated GoMock package.
package mock_apis

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStoreInterface is a mock of StoreInterface interface.
type MockStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStoreInterfaceMockRecorder
}

// MockStoreInterfaceMockRecorder is the mock recorder for MockStoreInterface.
type MockStoreInterfaceMockRecorder struct {
	mock *MockStoreInterface
}

// NewMockStoreInterface creates a new mock instance.
func NewMockStoreInterface(ctrl *gomock.Controller) *MockStoreInterface {
	mock := &MockStoreInterface{ctrl: ctrl}
	mock.recorder = &MockStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreInterface) EXPECT() *MockStoreInterfaceMockRecorder {
	return m.recorder
}

// AddProductsToStore mocks base method.
func (m *MockStoreInterface) AddProductsToStore(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddProductsToStore", w, r)
}

// AddProductsToStore indicates an expected call of AddProductsToStore.
func (mr *MockStoreInterfaceMockRecorder) AddProductsToStore(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProductsToStore", reflect.TypeOf((*MockStoreInterface)(nil).AddProductsToStore), w, r)
}

// GetProductsFromStore mocks base method.
func (m *MockStoreInterface) GetProductsFromStore(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetProductsFromStore", w, r)
}

// GetProductsFromStore indicates an expected call of GetProductsFromStore.
func (mr *MockStoreInterfaceMockRecorder) GetProductsFromStore(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsFromStore", reflect.TypeOf((*MockStoreInterface)(nil).GetProductsFromStore), w, r)
}
